1단계 - 문자열 계산기
g-oop/goop-java-lotto pull request #1
Opened 2024-02-06 15:16 UTC by boy0516

1단계 리뷰 부탁드립니다🙇🏻‍♂️ 
근데 브렌치가 메인밖에 없어요

2024-02-06 17:12 UTC, gilbertlim requested changes
로또 미션을 시작하셨네요!
코멘트 확인하시고 재요청부탁드려요!

2024-02-06 17:12 UTC, gilbertlim commented on src/main/java/Operator.java
> +public class Operator {
문자열 계산기를 구현하는 중이여서 'Operator' 는 연산자의 의미가  강해보여요!

2024-02-06 17:12 UTC, gilbertlim commented on src/main/java/calculator/alu/MethIngredient.java
> +public class MethIngredient {
MethIngredient 뜻이 무엇인가요?
Math 오타인가.. 궁금해요

2024-02-06 17:12 UTC, gilbertlim commented on src/main/java/calculator/alu/MethIngredient.java
> +        validationBlank(ingredient);
행위를 나타내는 메서드는 동사로 시작하는 것이 관례에요!

2024-02-06 17:12 UTC, gilbertlim commented on src/main/java/calculator/alu/MethIngredient.java
> +        if (validOperand(ingredient)) {
`isOperand()`가 의미상 더 적절해 보여요!

아래에 동일한 이름에 메서드가 있었군요..! 넘어가셔도 괜찮습니다.

2024-02-06 17:12 UTC, gilbertlim commented on src/main/java/calculator/alu/IngredientType.java
> +        return OPERAND.equals(this);
Enum 클래스는 == 비교해도 무방합니다.
equals 메서드 내부를 보면 == 비교하고 있어요.

2024-02-06 17:12 UTC, gilbertlim commented on src/main/java/calculator/alu/Calculator.java
> +            mainOperand = ALU.add(mainOperand, subOperand, currentOperator);
Alu 에서도 동일하게 equals 메서드를 사용 하네요. 중복 로직으로 보여요.
Alu의 역할이 무엇인지 고민해 볼 필요가 있어보여요.

2024-02-06 17:12 UTC, gilbertlim commented on src/main/java/calculator/alu/Alu.java
> +public class Alu {
Alu가 무슨 뜻인가요?

2024-02-06 17:12 UTC, gilbertlim commented on src/main/java/calculator/alu/Calculator.java
> +    private boolean mustOperator = false;
순서 때문에 사용되는 단순 플래그 변수로 보여요. 멤버변수로 선언했기 때문에 값을 변경하는 부분과 떨어져 있어 가독성이 떨어집니다. 지역변수로 처리할 수 있는 방법이 있을 것 같아요.

2024-02-06 17:12 UTC, gilbertlim commented on src/main/java/calculator/alu/Calculator.java
> +        methIngredients.forEach(this::progressCalculate);
예를 들어, index를 사용한다면 mustOperator 변수가 필요 없을 수 있을 것 같아요.

2024-02-06 17:12 UTC, gilbertlim commented on src/main/java/calculator/alu/Calculator.java
> +    private int mainOperand = 0;
lastOperand가 의미상 적절해 보입니다.

2024-02-06 17:12 UTC, gilbertlim commented on src/main/java/calculator/alu/Calculator.java
> +    private String currentOperator = "+";
`0 + {처음 값}` 로직이 무조건 수행되네요. `lastOperand = {처음 값}` 이라면 currentOperator는 필요 없어질 것 같아요.

2024-02-06 17:12 UTC, gilbertlim commented on src/main/java/calculator/alu/Alu.java
> +    public int add(int mainOperand, int subOperand, String operator) {
지금 구조는 연산자 하나가 추가/삭제 될 경우 많은 곳을 수정해야 합니다.
연산자 기호도 여러 곳에 흩어져 있고, 다형성에 취약합니다.
다형성 적용을 위해 Enum을 활용해볼까요?

2024-02-06 17:12 UTC, gilbertlim commented on src/test/java/calculator/alu/AluTest.java
> +        //given
given, when, then 없이 개행으로 구분할 수 있을 것 같아요.

2024-02-06 17:12 UTC, gilbertlim commented on src/test/java/calculator/alu/AluTest.java
> +        int result = alu.add(mainOperand, subOperand, operator);
alu의 모호한 역할이 여기서도 드러나네요. 더하기를 하는데 연산자가 인자로 들어가네요. 더하기 자체가 +인데 말이죠.

2024-02-06 17:12 UTC, gilbertlim commented on src/test/java/calculator/alu/AluTest.java
> +            .withMessage("덧셈 연산자 불일치: " + operator);
연산자 예외 테스트를 열심히 진행하셨네요!
Calculator에서 equals를 통해 연산자 일치 여부를 확인하고 Alu의 add 메서드를 호출하기 때문에 예외는 발생하지 않을 것 같습니다.

2024-02-09 14:26 UTC, boy0516 commented on src/main/java/calculator/alu/Alu.java
> +public class Alu {
산술 논리 장치(算術論理裝置, arithmetic and logical unit, ALU) 입니다.

2024-02-09 16:13 UTC, boy0516 commented on src/main/java/calculator/alu/Calculator.java
> +        methIngredients.forEach(this::progressCalculate);
음.. index 홀짝으로 하라는 말씀인가요?

2024-02-13 11:26 UTC, gilbertlim approved these changes
2단계 시작 전에 3번을 먼저 반영하고 시작해보세요.

1. 입력 값을 컬렉션에 담고
2. 컬렉션에서 추출할 때 연산자/피연산자를 구분하여
3. Enum에 정의된 연산자와 매핑된 함수를 통해 계산하고 (Enum에 계산 동작 구현)
4. 결과를 반환

2024-02-13 11:26 UTC, gilbertlim commented on src/main/java/calculator/calculator/OperatorType.java
> +public enum OperatorType {
Enum은 단순 열거 외에 동작도 정의할 수 있어요.
아래 문서에 잘 설명되어 있으니 참고해서 수정해보세요!


https://velog.io/@edgar6bf/Enum

2024-02-13 11:26 UTC, gilbertlim commented on src/main/java/calculator/calculator/Calculator.java
> +        OperatorType operator = status.getOperator();
ProgressStatus는 계산 과정 중 상태를 관리하는 변수들을 래핑한 것으로 보이네요.
래핑하지 않고 lastOperand 등 변수를 Calculator의 멤버 변수로 관리하는 방법도 있어 보입니다.

포장 객체로 담아서 처리하다가 결국은 get을 사용해서 꺼내쓰니까요.

추가적으로, getter를 사용할 때는 getter가 있는 클래스의 역할이 외부로 나온 것이 아닌지 체크해 보면 좋아요.

2024-02-13 11:26 UTC, merged